"""Add cad_object_key to CADModel

Revision ID: 869d4f824bd7
Revises: e421475dba3c
Create Date: 2021-07-02 16:00:50.041452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869d4f824bd7'
down_revision = 'e421475dba3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cad_models', sa.Column('cad_object_key', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cad_models', 'cad_object_key')
    # ### end Alembic commands ###
